stages:
  make_dataset:
    cmd: python src/data/make_dataset.py
    deps:
    - data/raw/train/data-00000-of-00001.arrow
    - data/raw/validation/data-00000-of-00001.arrow
    - data/raw/test/data-00000-of-00001.arrow
    - src/data/make_dataset.py
    outs:
      - data/processed/train_loader.pt
      - data/processed/validation_loader.pt
      - data/processed/test_loader.pt


  train:
    cmd: python src/models/train_model.py 1
    deps:
    - data/processed/train_loader.pt
    - data/processed/validation_loader.pt
    - src/models/train_model.py
    outs:
    - models/trained_model.pt
    - models/emissions.csv


  evaluate:
    cmd: python src/models/test_model.py
    deps:
      - data/processed/test_loader.pt
      - src/models/test_model.py
      - models/trained_model.pt
    outs:
      - models/test_metrics.csv
