artifact_location: file:///C:/Users/joano/Mis documentos/Master_in_Data_Science/Q3/MLOps/MLOps-TeamBeans/zxczx/0
creation_time: 1697581005655
experiment_id: '0'
last_update_time: 1697581005655
lifecycle_stage: active
name: Default
